Revert "Bump ruby to 2.3.1"
This reverts commit fefcc4e6967e2ebabe4e7ab0ad444638dcf7a293.

CircleCI hasn't supported Ruby-2.3.1 yet?

bundler: failed to load command: cap (/home/ubuntu/masutaka.net/vendor/bundle/ruby/2.3.0/bin/cap)
NoMethodError: undefined method `activate_bin_path' for Gem:Module
  /home/ubuntu/masutaka.net/vendor/bundle/ruby/2.3.0/bin/cap:22:in `<top (required)>'